### ISSUE TITLE
--stale option doesn't work on Elixir v1.7.*

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [lpil/mix-test.watch#102]
When executing `mix test.watch --stale` I get the following output for my tests:

```
Running tests...
Cover compiling modules ...
No stale tests
Unknown switch: --stale

```

The last line, `Unknown switch: --stale` is red and it is an Error. 
From my understanding of the documentation, this is not an expected behaviour.

**Comment by lpil** [comment]
Hi @Fl4m3Ph03n1x. I'm unable to produce, could you supply a repo with a minimal recreation of the problem please?

**Comment by Fl4m3Ph03n1x** [comment]
Hey, sure!
I have created a standard mix project and uploaded it here:
https://github.com/Fl4m3Ph03n1x/watchtest

You can fork it and hopefully reproduce the issue. 

What did I do to create this basic project?
1. mix new project_name
2. Create config files
3. Install mix-test.watch
4. Install credo
5. mix deps.get
6. mix text.watch --stale

**Comment by Fl4m3Ph03n1x** [comment]
Which elixir version are you using?
If you can't replicate the issue, it may be a problem with the elixir version. I tested this using 1.7.3 with erlang 21.

**Comment by lpil** [comment]
In your `dev.exs` you have specified the tasks as `test --cover` and `credo --strict`. The flags are passed to all tasks which results in the credo task erroring.

**Comment by Fl4m3Ph03n1x** [comment]
Got it. Thanks for your time. I have now checked the README and I believe the section _Passing Arguments To Tasks_  could be updated to mention that if you pass an argument to some task and that task doesn't know that argument, the process will halt. 

Again, this is fairly obvious once you know how tasks work and are able to make the necessary inferences, but alas it was not obvious to me.

What would be your opinion on this?

**Comment by lpil** [comment]
We can't add that because we don't know anything about the task being run. Some tasks will accept it, others will not.

We do say this, which I think is all we can be certain of:

> Note that if you have configured more than one task to be run these arguments will be passed to all the tasks run, not just the test command.
