### ISSUE TITLE
zombie_killer script not shipping with package

### ISSUE THREAD

**Issue by TheFirstAvenger** [lpil/mix-test.watch#108]
The latest release (`v1.0.0`) tries to run `_build/dev/lib/mix_test_watch/priv/zombie_killer` however that file does not ship with the package.
`_build/dev/lib`:
<img width="364" alt="Screen Shot 2019-10-25 at 11 10 00 AM" src="https://user-images.githubusercontent.com/8557871/67582559-02d06b80-f718-11e9-8880-b1e38c65f512.png">
`deps/`:
<img width="245" alt="Screen Shot 2019-10-25 at 11 10 57 AM" src="https://user-images.githubusercontent.com/8557871/67582657-298ea200-f718-11e9-852e-bcab6c7d11cf.png">

**Comment by lpil** [comment]
Thank you, I've released a new version.
