### ISSUE TITLE
Ability to exclude files/directories

### ISSUE THREAD

**Issue by blacksails** [lpil/mix-test.watch#11]
When I generate a migration using ecto migrate, the test are automatically run. This causes the test environment to run the migration. The problem is that at that point the migration is empty. If I then add my changes to the migration, I cannot migrate the test environment without a migration rollback or database wipe.
I could fix this by disabling the automatic migration of the test environment, but I actually like that the environment is automatically migrated. It would be cool to be able to make the watcher ignore the migrations directory.

**Comment by lpil** [comment]
Oh dear, that sounds very annoying. A good feature idea, for sure.
