### ISSUE TITLE
Interactive watch mode

### ISSUE THREAD

**Issue by randycoulman** [lpil/mix-test.watch#115]
I've been using and loving this project for years now. Thank you so much for creating and maintaining it for so long!

After spending some time in the JavaScript world, I fell in love with [Jest](https://jestjs.io/)'s interactive watch mode. While it's not really documented, [this short video](https://egghead.io/lessons/javascript-use-jest-s-interactive-watch-mode) gives a good overview of it.

I've created a new project, [mix_test_interactive](https://github.com/randycoulman/mix_test_interactive), that is largely a clone of this one, but with an interactive mode added.  It's got some basic functionality already implemented and I'm actively working to make it better.

If you are interested, I'd be happy to contribute my work back to this project instead of maintaining a separate one.  If you're not interested, that's totally fine!

I didn't start with a fork and a PR because I wasn't sure if you'd be interested in what I've done. From what I can tell, GitHub makes it very difficult to decouple a forked repo from its parent.  I have not yet published my project to hex.pm because I don't want to cause confusion if we can combine our work in one place.

Let me know what you think. I look forward to hearing from you!

**Comment by lpil** [comment]
Hey @randycoulman ! Very cool!

I'm afraid I'm mostly working on [Gleam](https://github.com/gleam-lang/gleam/) these days so I've not much time to work on or maintain Elixir projects. With this in mind it's probably best to keep the projects apart.

I would be open to a PR in the README noting that this alternative exists.

**Comment by randycoulman** [comment]
Thanks for the quick response! Once I'm ready to actually release to hex.pm, I'll submit a PR here with a link.
