### ISSUE TITLE
Run only tests from changed file?

### ISSUE THREAD

**Issue by praveenperera** [lpil/mix-test.watch#12]
Is it possible to only run the tests associated with the file that was changed? So for example if `web/controllers/page_controller.ex` to only run the tests in `test/controllers/page_controller_test.ex`. 

Then it should also run if the `page_controller_test.ex` is changed.

This is how [kovacs](https://github.com/antp/kovacs) works.  It would be awesome to get the functionality of kovacs with the ease of use of mix test.watch

**Comment by lpil** [comment]
It doesn't currently do this, but it's a nice idea. For now, you can pass in the path to the file to test, like you would with `mix test`.

**Comment by trinode** [comment]
I was going to suggest the same thing  (even down to mentioning Kovacs), it'd be pretty awesome.

**Comment by bigardone** [comment]
Me too, this would be really awesome for projects with a large test suite.
BTW thanks for this great library  :)

**Comment by lpil** [comment]
Thank you :)
