### ISSUE TITLE
** (Mix) The task "test.watch" could not be found

### ISSUE THREAD

**Issue by eliknebel** [lpil/mix-test.watch#124]
I followed the instructions and added as a dependency to deps in `mix.exs` and ran `mix deps.get`:
```
{:mix_test_watch, "~> 1.0", only: :dev, runtime: false},
```

But I'm receiving the following error when trying to run:
```
$ mix test.watch
** (Mix) The task "test.watch" could not be found
```

which is strange because at one point this command was working for me but no longer is

```
$ elixir -v
Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.11.4 (compiled with Erlang/OTP 23)
```

**Comment by lpil** [comment]
How strange! I can't be sure what the issue is. Can you share the project?

**Comment by eliknebel** [comment]
Sure can! It's open source -> https://github.com/Simon-Initiative/oli-torus

Really appreciate you taking a look. It sure would be nice to get this working again, it is a very useful for unit testing.

**Comment by lpil** [comment]
I cloned the repo and ran `mix deps.get && mix test.watch`, which ran the tests. Is there an entry for this project in `deps` and`_build`?

**Comment by eliknebel** [comment]
Aha, I've identified the problem. After you mentioned `_build`, I noticed that it wasn't in the test subdirectory and we had a configuration in `mix.exs` to run this command in the `:test` environment. After commenting that, it works as expected:

```
      preferred_cli_env: [
        test: :test,
        # "test.watch": :test,
        coveralls: :test,
        "coveralls.detail": :test,
        "coveralls.post": :test,
        "coveralls.html": :test,
        "coveralls.xml": :test
      ],
```

Thanks so much for your help!
