### ISSUE TITLE
Automatically run deps.get when missing dep

### ISSUE THREAD

**Issue by grantwest** [lpil/mix-test.watch#125]
So you are working and add a dependency to your project and then your `test.watch` starts producing this error:

```
Running tests...                                                                                                                        
Unchecked dependencies for environment test:                                                                                            
* libgraph (Hex package)                                                                                                                
the dependency is not available, run "mix deps.get"                                                                                   
 ** (Mix) Can't continue due to errors on dependencies
```

It knows exactly what is happening and how to fix the issue. All that needs to be done is run a `mix deps.get`. Maybe the test watcher should run this automatically when this error is given?

**Comment by lpil** [comment]
Good idea but I'm afraid I'm not planning to add new new features to this tool. Perhaps try https://github.com/influxdata/mix_test_interactive
