### ISSUE TITLE
Prevent execution of commands of mix :dev environment

### ISSUE THREAD

**Issue by nandofarias** [lpil/mix-test.watch#127]
Hey folks,

`mix_test_watch` is amazing, I'm using it in a lot of different projects, but recently I noticed a strange behavior in one of the projects I'm working on right now. It heavily uses a pattern of setting `System.put_env/2` on the `dev.secret.exs` file, turns out this file runs all those commands when using `mix test.watch` causing some different behaviors on the application.

It's not so common to see this pattern, but a minimal way of reproducing that behavior is:

- creating a new application `mix new my_app`
- create a `config/config.exs` file with this configuration
```elixir
use Mix.Config

if Mix.env() == :dev do
  System.put_env("FOO", "bar")
end
```
- add `IO.inspect(System.get_env("FOO"))` to `lib/my_app.ex`
```elixir
def hello do
    IO.inspect(System.get_env("FOO"))
    :world
end
```
- run `mix test`
- add  mix_test_watch
- run `mix test.watch`

When running with `mix test` you should see nil on the console, but when running with `mix test.watch` the "bar" is printed to the console.

A good way to workaround this is changing the `mix.exs` file to 

```elixir
 defp deps do
    [
      :mix_test_watch, "~> 1.0", only: [:dev, :test]}
    ]
end
```

and  adding the `preferred_cli_env` to "test.watch" as :test

```elixir
def project do
    [
      app: :my_app,
      version: "0.1.0",
      elixir: "~> 1.12",
      start_permanent: Mix.env() == :prod,
      preferred_cli_env: [
        "test.watch": :test
      ],
      deps: deps()
    ]
  end
```

What do you think about that? Would love to hear concerns about this approach.

**Comment by lpil** [comment]
That sounds like a good way to resolve that issue to me.

**Comment by nandofarias** [comment]
Cool, thank you @lpil! Do you think that it would be helpful to update de readme with those instructions?

**Comment by lpil** [comment]
Sounds good to me

**Comment by nandofarias** [comment]
Thank you @lpil
