### ISSUE TITLE
** (Postgrex.Error) ERROR 40P01 (deadlock_detected) deadlock detected

### ISSUE THREAD

**Issue by icecapp** [lpil/mix-test.watch#130]
When running my tests with `mix test` everything passes.

When running my tests with `mix test.watch`, everything passes on the first run.

On subsequent runs, a random number of tests start failing with:

```elixir
     ** (Postgrex.Error) ERROR 40P01 (deadlock_detected) deadlock detected
     
         hint: See server log for query details.
     
     Process 89508 waits for ShareLock on transaction 654039; blocked by process 89506.
     Process 89506 waits for ShareLock on transaction 654025; blocked by process 89508.

```
     
Any ideas what could be causing this ?

**Comment by lpil** [comment]
I would guess that your application performs some database queries when it boots and the multiple running instances of your application are interfering with each other.

**Comment by icecapp** [comment]
had another hidden terminal open with `mix test.watch` running. Thanks for the response and my bad !
