### ISSUE TITLE
Config.env() is deprecated

### ISSUE THREAD

**Issue by ballPointPenguin** [lpil/mix-test.watch#132]
I'm using elixir 1.13.2

I needed this to make `config :mix_test_watch ...` work properly:

```ex
if config_env() == :test do
  config :mix_test_watch,
    clear: true
end
```

and no `use Mix.Config`

Maybe make a note in the README

PS It was not working for me with only `:dev`, I needed to specify `:test`. I'm not sure if that's a version-related change as well.

**Comment by tobyhinloopen** [comment]
I'd just put it in `test.exs`

**Comment by tobyhinloopen** [comment]
I'd put it in `config/dev.exs`. (yes, not in `config/test.exs`)

```
config :mix_test_watch, extra_extensions: [".heex"]
```
