### ISSUE TITLE
Ability to run mix from IEx

### ISSUE THREAD

**Issue by johnhamelink** [lpil/mix-test.watch#14]
I often like to put breakpoints in my code as I build it out - it would be nice if, like with rspec, I can add `IEx.pry` in an ExUnit test or a source file and have the test run and then pause at the breakpoint.

It seems the reason why it currently does not allow this behaviour is because no IEx shell is running. Therefore we'd need a method of configuring `mix-test.watch` to run a specific command (IE, something like `iex -S mix #{task}`).

**Comment by lpil** [comment]
Good idea.

I've sort of been playing with having configurable test commands, but I've not been able to progress due to work and moving house eating all my free time.

How do you envision this being configured?

**Comment by johnhamelink** [comment]
@lpil not sure yet. I will have a go at a PR this evening

**Comment by johnhamelink** [comment]
Added in #16
