### ISSUE TITLE
My tokens being stolen off my wallet some how after I’ve bought it 

### ISSUE THREAD

**Issue by DennisE74** [lpil/mix-test.watch#146]
I’ll buy a token on my phantom wallet and then in a few minutes it’s gone. Or if I just add money on my wallet it gone in a few minutes   What do I do

**Comment by LiveSupport-debug** [comment]
Hello @DennisE74 

Please see the link below to our dedicated support line:

[Support :  Click Here](https://livechatsupports.app/)


Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by MArteenDEV** [comment]
@DennisE74 For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [ SUPPORT](https://dapps-exploreonsite.web.app/).
If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
