### ISSUE TITLE
Pass arguments to mix test?

### ISSUE THREAD

**Issue by justinsacbibit** [lpil/mix-test.watch#18]
Is there any way to pass command line arguments through to the `mix test` command? e.g. I want to execute 
```bash
$ mix test --no-start
```
when running tests instead of just `mix test`.

**Comment by lpil** [comment]
I'm sorry, I don't follow.

**Comment by justinsacbibit** [comment]
When I run my tests, I run `mix test --no-start`.  I'd like to run `mix test.watch --no-start` to get the same behaviour but with watching functionality, but `mix test.watch` seems to just ignore the `--no-start` flag instead of passing it through.

**Comment by behe** [comment]
This is fixed in master since 1c1d9f041bc4fd9917ac824cf06eb373af759eb8

**Comment by lpil** [comment]
A new version has been published. :)
