### ISSUE TITLE
Error/warning on test with a config

### ISSUE THREAD

**Issue by AdamBrodzinski** [lpil/mix-test.watch#28]
When I start a hello world app with a basic test I get the following warning when I use the config

```
config :mix_test_watch,
  clear: true
```

```
Running tests...
You have configured application :mix_test_watch in your configuration
file but the application is not available.

This usually means one of:

1. You have not added the application as a dependency in a mix.exs file.

2. You are configuring an application that does not really exist.

Please ensure :mix_test_watch exists or remove the configuration.

..

Finished in 0.02 seconds (0.02s on load, 0.00s on tests)
2 tests, 0 failures
```

However if I add it to the applications as the warning suggests I get the error:

```
my_app|⇒ mix test.watch

Running tests...

=INFO REPORT==== 24-Apr-2016::14:48:58 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application mix_test_watch: could not find application file: mix_test_watch.app
```

Is it possible to have mix-test.watch clear out the console without printing the warning?

<br>
Elixir 1.2.1
Erlang/OTP 18 erts-7.2.1

```
defmodule MyApp.Mixfile do
  use Mix.Project

  def project do
    [app: :my_app,
     version: "0.0.1",
     elixir: "~> 1.2",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [applications: [:logger]]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:mix_test_watch, "~> 0.2", only: :dev},
    ]
  end
end
```

**Comment by lpil** [comment]
What happens when you add mix_test_watch to the list of applications (only in dev).

**Comment by AdamBrodzinski** [comment]
Did you mean add `mix_test_watch` or `: mix_test_watch` ? If I add the symbol in dev I get:

```
my_app|⇒ mix test.watch

Running tests...

=INFO REPORT==== 24-Apr-2016::14:48:58 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application mix_test_watch: could not find application file: mix_test_watch.app
```

**Comment by lpil** [comment]
It seems that we cannot use mix config unless we register as an application. Hm. This is not ideal if that is the case.

**Comment by lpil** [comment]
I've tried to replicate this and I get no such warning when I add config without adding an application by the same name, and I now realise I've been doing this for some time.

Here are example projects:

https://github.com/lpil/fawkes/blob/master/config/dev.exs#L56-L57
https://github.com/lpil/fawkes/blob/master/mix.exs#L22-L23

https://github.com/lpil/mars/blob/master/config/config.exs
https://github.com/lpil/mars/blob/master/mix.exs#L16

**Comment by coryodaniel** [comment]
@lpil I was having the same issue, wrapping it in the Mix env absolutely worked for me too.

**Comment by lpil** [comment]
What do you mean by wrapping it in the Mix env?

**Comment by coryodaniel** [comment]
```if Mix.env == :dev do```

**Comment by AdamBrodzinski** [comment]
@coryodaniel thanks for the info. I'm using Phoenix so I just added the `config :mix_test_watch, clear: true` to `config/dev.exs` and the error goes away as well.

@lpil I'll submit a PR to add a note on the readme to make this more clear. I think that should allow us to close out this issue?
