### ISSUE TITLE
Add support for additional file types

### ISSUE THREAD

**Issue by daveshah** [lpil/mix-test.watch#35]
Currently, watched file types are hardcoded within the Path module. Nice to have file types (like .haml) aren't currently supported, and therefore aren't picked up in projects using alternative templating (like [Phoenix Haml](https://github.com/chrismccord/phoenix_haml) )

It would be nice to have the option to include file types through the config similarly to how exclusion works.

**Comment by jameslutley** [comment]
Would it be possible to add [Phoenix Slime](https://github.com/slime-lang/phoenix_slime) to this? It seems to be quite a popular templating engine in Phoenix.

**Comment by jameslutley** [comment]
Thanks for the tip, `extra_extensions` did the trick.
