### ISSUE TITLE
run dependent tests when source file changes

### ISSUE THREAD

**Issue by sunaku** [lpil/mix-test.watch#42]
Hello,

I was looking into switching to this tool from [a shell script I wrote](https://github.com/sunaku/home/blob/master/bin/inotifytest-elixir-mix) :neckbeard: that does nearly the same thing.

However,  I noticed that this tool runs _all_ tests whenever a source file changes.  This makes my TDD feedback loop longer than I'd like because I have to wait for unrelated tests to finish running. :snail:

Instead, when I modify a `lib/*.ex` file, I only want its corresponding test and any _dependent_ tests to run.  For example, my shell script does this by running `mix compile` and looking at what files are recompiled.  Then, it maps each of those recompiled source files to their corresponding tests and runs them too. :santa: 

Thanks for your consideration.

**Comment by lpil** [comment]
Oddly enough a talk I gave at the London Elixir meetup inspired a feature in Elixir core that does this. `mix test --stale`. It's coming out in v1.3.
