### ISSUE TITLE
Does not work on 1.3.0

### ISSUE THREAD

**Issue by jbr** [lpil/mix-test.watch#43]
with elixir 1.3.0, mix_test_watch 0.2.6, I get:

```
⇒ mix test.watch

Running tests...
** (TokenMissingError) nofile:1: missing terminator: ) (for "(" starting at line 1)
    (elixir) lib/code.ex:168: Code.eval_string/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:651: Enum.each/2
    (mix) lib/mix/tasks/run.ex:67: Mix.Tasks.Run.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (elixir) lib/enum.ex:651: Enum."-each/2-lists^foreach/1-0-"/2
```

when `mix test` runs and passes.

Normally I'd try to do some digging to figure out what's going on, but I'm not sure where to look with that anonymous stack trace.  Let me know if there's additional information about my project I can provide (if this is not a general problem)

**Comment by stwf** [comment]
I see this too

**Comment by lpil** [comment]
Well this looks rather grim. :(

**Comment by lpil** [comment]
I think this is a bug in mix. https://github.com/elixir-lang/elixir/issues/4861

**Comment by mikrofusion** [comment]
fyi - I just confirmed this is fixed by upgrading to elixir 1.3.1.

```
brew update
brew upgrade elixir
```

**Comment by lpil** [comment]
Thanks!

**Comment by willcodeforfoo** [comment]
Confirmed, saw this on Elixir 1.3.0, upgrading to 1.3.1 fixed it.
