### ISSUE TITLE
:init.restart()

### ISSUE THREAD

**Issue by josevalim** [lpil/mix-test.watch#45]
I am not sure this is the best way to let you know but I have just found out there is a command called :init.restart() that will restart the whole system, shutting down all applications and starting them again. For example, if you do:

``` iex
$ iex -S mix test
iex> :init.restart()
```

It will restart everything and run the tests again. Maybe this can be used to make this project much more straight-forward. :)

**Comment by josevalim** [comment]
Related gist which may help you with further ideas: https://gist.github.com/josevalim/a5e747c90a72e40a4b52062ea6919877

**Comment by lpil** [comment]
Gosh. Suddenly all that work seems a bit pointless. :P

**Comment by josevalim** [comment]
I think we still need the watching bit, just the restart bit that got much much easier! :D

**Comment by lpil** [comment]
The watching is easy thanks to `fs`.

One of the features I want is having IEx running at the same time so that one can type expressions in the repl while the tests are not running. If we use `:init.restart/0` we'll lose the state each time the tests run. :(

**Comment by josevalim** [comment]
>  If we use :init.restart/0 we'll lose the state each time the tests run. :(

Yes :(

**Comment by lpil** [comment]
Perhaps we can support both once we get test modules closing after an exception is thrown when compiling them. (keen to take a stab at this myself, but have had a busy week)

There are advantages to each method. The `init` one wipes clean all state and works for versions of Elixir that don't have the test module closing, the other one gives us the repl and might be a touch faster (?).

**Comment by josevalim** [comment]
Yeah, it may be faster with the risk of potentially running on outdated state.

**Comment by lpil** [comment]
Yes I think people have had problems with state in Phoenix applications already. I need to find some time to read the rebar3 autotest plugin so I can see how it is managed there. It re-uses the VM and features a repl.

**Comment by lpil** [comment]
Closing as  `--listen-on-stdin` exists now
