### ISSUE TITLE
Add a way to run other mix tasks as well as test

### ISSUE THREAD

**Issue by lpil** [lpil/mix-test.watch#5]
I'm looking at you, [dogma](http://github.com/lpil/dogma).

**Comment by optikfluffel** [comment]
Is this implemented yet? Looks like it at [README](https://github.com/lpil/mix-test.watch#running-additional-mix-tasks) but I can't get it to work.
I just get `The task "dogma" could not be found`.

**Comment by lpil** [comment]
It is! Have you specified dogma as a test dep?

**Comment by optikfluffel** [comment]
Thanks, my fault. I specified dogma as `only: :test` dep.

**Comment by lpil** [comment]
Glad I could help.
