### ISSUE TITLE
Specifying filter with describe: does not work

### ISSUE THREAD

**Issue by gasparch** [lpil/mix-test.watch#50]
runinng `mix test.watch test/ --only describe:"function/1"` does not work, skips all tests. In other hand  `mix test test/ --only describe:"function/1"` works as expected and runs only tests in specified describe block.

**Comment by lpil** [comment]
Thanks :)

**Comment by zhhz** [comment]
I'm having the same situation here:

`$ mix test.watch --exclude integration`

I also tried to put following in config.exs
`
if Mix.env == :dev do
  config :mix_test_watch, exclude: [~r/THE+FOLDER/]
end
`
No luck here either

**Comment by lpil** [comment]
This tool doesn't pass share config with mix test via config.exs. It is supposed to via command line flags though, thanks for the report

**Comment by zhhz** [comment]
Hi Louis,

Thanks for the response. First I have to say you did wonderful job on the mix_test_watch. I use it pretty much every day.

Now about my question, can you give me an example for passing the flags by using cmd line? i.e. I want to exclude all the test cases tagged with integration.

Thanks.

**Comment by lpil** [comment]
It should work the way you specified, I think this is a bug.

**Comment by zhhz** [comment]
Thanks Louis. I didn't try to generate a PR, because I'm just a beginner of Elixir, maybe in the future I'll contribute...

Again, thanks for taking care this issue...

**Comment by lpil** [comment]
No worries. I'll have a look when I have some time :)

**Comment by lpil** [comment]
I think that e28b8aa0050efd6b686e9f0e863a7039871af40d may have fixed it. Could you try the new version I pushed and let me know if it works?

Thanks

**Comment by zhhz** [comment]
Awesome, I'll give it a run once I get home. Thanks.

**Comment by zhhz** [comment]
Works like a charm!!! Thanks!

**Comment by lpil** [comment]
Great, thanks
