### ISSUE TITLE
Does not play well with Ecto Migrations

### ISSUE THREAD

**Issue by unclesnottie** [lpil/mix-test.watch#52]
If you use `mix ecto.gen.migration` while mix-test.watch is running, the empty migration gets applied immediately.  Then when you update the file with the code for your DB change, it won't get applied in the test env.  Currently you have to remember to stop mix-test.watch before generating a migration.  Otherwise, you have to drop/create/migrate your test DB once you've finished your migration.

It would be nice if mix-test.watch either ignored the `priv/repo/migrations` directory or prompted the user before running the tests when the change involves migrations.  This would allow a user to more easily prevent this situation.

**Comment by lpil** [comment]
Ignoring priv/repo/migrations sounds good. Want to have a go? :)

**Comment by mkaszubowski** [comment]
@lpil doesn't adding migrations to `config :mix_test_watch, exclude: ...` solve the issue? If you want it added as a default, I'd be happy to send you a pull request, just let me know :)

**Comment by lpil** [comment]
Sounds like a sensible default.

**Comment by lpil** [comment]
This has been done :)
