### ISSUE TITLE
Stopping on first failed test

### ISSUE THREAD

**Issue by gasparch** [lpil/mix-test.watch#53]
Hi! 

I've tried to implement functionality to stop mix test output after detecting first failed test. In this case running something `mix test.watch --stop-on-failure --seed 0 tests/` allows work one by one on each failing tests during refactoring. 

Here is the change against v0.2.6 - https://github.com/gasparch/mix-test.watch/tree/stop_on_failure

Does it make sense to you? If yes, I'll try to merge it to main tree, as I see a lot of changes happened since v0.2.6 ;)

Here is a discussion in elixir-lang (https://github.com/elixir-lang/elixir/issues/4586), but looking on ExUnit sources adding this kind of functionality will be really difficult in there.

What do you think?

**Comment by lpil** [comment]
Hey! I feel that with the `--stale` flag this isn't needed so much. Where would this be more practical?

**Comment by gasparch** [comment]
If you have 100 tests and 15 of them are failing - stale will rerun them each time and show output of all 15 failing tests. Proposed option allows you to see only one test's output, so on each rerun you will see this test's output until you fix it, then it will automatically change to next failing one.

Right now my work flow looks like running tests, scrolling up, finding line number, running it with --only line:999, fixing the case, then running all tests again, finding another failing one and etc. Usually smaller/simpler tests are located on the top of the file, so when refactoring you want to work from top to bottom of test file to slowly fix both code and tests.

**Comment by lpil** [comment]
OK, that makes sense. :)

I think this would actually be useful in ExUnit itself rather than just in this helper. Let's add it there. :)

**Comment by gasparch** [comment]
I tried to add it to ExUnit but failed ;((( it seems it is designed to run tests concurrently, so stopping output reliable just after failed test did not worked for me (even with --trace which runs one test a time).

**Comment by lpil** [comment]
Perhaps see if you can get an issue opened and then maybe someone else can do it. This isn't the right place to add this.

**Comment by gasparch** [comment]
They say it is low priority and nobody wants to work on it ;) https://github.com/elixir-lang/elixir/issues/4586
