### ISSUE TITLE
Random failures

### ISSUE THREAD

**Issue by alex88** [lpil/mix-test.watch#54]
I wrote a small library for internal use that uses redis for some queues handling.

Now, one thing that I've noticed is that while saving sometimes the test fails, looking at redis messages everything seems working correctly, but test fails pretty often on tests with multiple asserts, like 20-30% of the times.

Trying instead with a bash script `while mix test --raise; do :; done` runs thousands of time without a failed test.

Could be something in this library that could cause the issue? Because is the only variable between these two tests.

**Comment by alex88** [comment]
I'll add an example, I've this test code which calls a library that pushes/pops messages in queues:

```
test "returns the last messages in queue in order" do
  Queue.enqueue(%{message: "1", queue: "bar"})
  Queue.enqueue(%{message: "2", queue: "foo"})
  Queue.enqueue(%{message: "3", queue: "bar"})
  assert Queue.pop == {:ok, %{message: "1", queue: "bar"}}
  assert Queue.pop == {:ok, %{message: "2", queue: "foo"}}
  assert Queue.pop == {:ok, %{message: "3", queue: "bar"}}
end
```

this is a redis excerpt from `redis-cli monitor`

```
1478567296.690655 [0 lua] "RPUSH" "bar" "1"
1478567296.690876 [0 lua] "RPUSH" "foo" "2"
1478567296.691021 [0 lua] "RPUSH" "bar" "3"
1478567296.691156 [0 lua] "LPOP" "bar"
1478567296.691284 [0 lua] "LPOP" "foo"
1478567296.691413 [0 lua] "LPOP" "bar"
```

which should return the messages in order as they were pushed. This is the test exception I get:

```
1) test Queue.pop/0 returns the last messages in queue in order (GoalshouterQueue.QueueTest)
     test/lib/goalshouter_queue/queue_test.exs:54
     Assertion with == failed
     code: Queue.pop() == {:ok, %{message: "1", queue: "bar"}}
     lhs:  {:ok, %{message: "2", queue: "foo"}}
     rhs:  {:ok, %{message: "1", queue: "bar"}}
     stacktrace:
       test/lib/goalshouter_queue/queue_test.exs:58: (test)
```

so it first got the second message instead of the first one. However, all 3 asserts has run (because I can read the messages in the redis log), it seems like the asserts are not in sync with the lines of code.

**Comment by alex88** [comment]
Nvm, my fault :( Had another process running in background duplicating the tests :(

**Comment by lpil** [comment]
oops! Glad you found the problem :)
