### ISSUE TITLE
Ability to focus on some tests...

### ISSUE THREAD

**Issue by ijcd** [lpil/mix-test.watch#55]
It would be nice if we could focus on some tests for a brief time:

```
@tag wip
test "should do foo" do
...
end
```

Ideally it would only run tests marked with some tags (if present) otherwise it should fall back to running everything as it normally does.

**Comment by lpil** [comment]
This would be a feature of `ExUnit` rather than this project, no?

**Comment by ijcd** [comment]
It could be implemented there, but it might be simpler to have something like this in test.watch:

```
  config :mix_test_watch,
    tasks: [
      ["test --only wip", stop_on_failure: true],
      "test",
      "credo",
      "dialyzer",      
    ]
```

Something like this would allow for varying workflows.

**Comment by lpil** [comment]
I think this should be an ExUnit feature.
