### ISSUE TITLE
File changes not notified in Docker

### ISSUE THREAD

**Issue by cliffrowley** [lpil/mix-test.watch#61]
Docker for Mac, all versions that I've tried.  I don't know about other versions of Docker.  The watcher waits but nothing happens, basically, but I think it's actually a bug (or limitation) in Docker for Mac itself or the way it operates, but I am reporting it here so that it can be logged and thus so can a potential workaround.

I will take a look into this myself anyway, as I am able to use `inotifywait` manually and watch file changes - but only if I use something like `-qre attrib`.  This only tool isn't the only one having issues something is definitely wonky somewhere.

**Comment by lpil** [comment]
I'm not a mac user, but last time I played with one I found that the virtualbox guest the docker container lived inside didn't get filesystem events when a file was edited on the host. Perhaps I was wrong. I think there is a new version of docker for mac that does not use virtualbox, is that right?

Do you know what `-qre attrib` does? :)

**Comment by cliffrowley** [comment]
Docker for mac does indeed not use VirtualBox any more.  And yes, I know what `-qre attrib` does - I should have been more specific.  I've been auto testing thus far by running `inotifywait -qre attrib $DIRS` in a shell script simply because it's the _only_ way I've been able to get a consistent notification when a file changes in my source directory.  I keep revisiting this issue every couple of weeks but I've still not been able to solve it, though I do now get other file system events - but it seems most watchers still don't work.

**Comment by lpil** [comment]
Cool, thank you!

Currently this project is a slightly weird unfinished state on master. As there's good reason to fix it up I'll do so over the next few days.

This is the project we use for watching the file system https://github.com/synrc/fs

If you could get a little script working with that in docker than we will be able to leverage that code here :)

**Comment by cliffrowley** [comment]
I've identified that the problem is in the fs module, specifically the 0.9.x branch.  I don't know what the bug is, but I do see that updating mix-test.watch deps to fs 2.12.x will conflict with phoenix_live_reload - which is a problem.

I guess I'll see if there's any reason phoenix_live_reload can't update their fs, or figure out what the problem is in the 0.9 branch and seeing if I can fix that and submit a PR for a patch..

**Comment by cliffrowley** [comment]
Alrighty, so it seems that phoenix_live_reload is updated in master already, so I think what I'll do for now (personal workaround) is to fork your 0.2.6 branch with its dependencies updated to fs 2.x, until phoenix_live_reload tag a release.  In which case if you're working on what's in master it might be worth pointing it at fs 2.x instead - at least then when you're done you'll already be using the same version.

**Comment by cliffrowley** [comment]
Heh wow, they've released already!  So if you push a 0.2.7 with fs pointing at 2.12.0 then it should all be sorted!

**Comment by cliffrowley** [comment]
So this is my temporary workaround until mix-test.watch master is released or a new 0.2.x is pushed with updated the fs dependency:

    {:mix_test_watch, "~> 0.2", github: "cliffrowley/mix-test.watch", branch: "v0.2.6-docker", only: :dev}

I tried to submit a PR but since I'm working off a branch which is based off a tag so the branch doesn't exist in your repo, github instead wants me to submit a PR against your master, so I'll have to leave that one in your hands I'm afraid.  I can verify it all works swimmingly with the update fs dependency at least.

**Comment by FalloutX** [comment]
Just want to pitch in here to say that I am just testing the water with elixir with a Vagrant Machine(using [synced folders](https://www.vagrantup.com/docs/synced-folders/) ), and when I edit a file on the host the tests don't run. However they do run when I edit the file on a guest machine. I think due to the synced folder work with Virtual Box, the file system events that `mix test.watch` depends on, don't trigger.

**Comment by cliffrowley** [comment]
That's unfortunate for VirtualBox.  Thankfully it _is_ working with Docker for Mac with my patched branch (not sure if @lpil is going to fix this or not, but it _will_ need to be fixed now that Phoenix have updated their dependency).

**Comment by lpil** [comment]
Could you try with master please @cliffrowley ? :)

**Comment by cliffrowley** [comment]
I can indeed. You mentioned before that master needed some work before
releasing, does that mean it's ready to go?

**Comment by lpil** [comment]
Theoretically yes but it's been about a year since the last release and I'm nervous I've broken something. :P

**Comment by cliffrowley** [comment]
It could be safer to release a patch for the previous release as well,
knowing that it works.

**Comment by lpil** [comment]
I believe this is fixed on master.
