### ISSUE TITLE
Update the fs dependency

### ISSUE THREAD

**Issue by PragTob** [lpil/mix-test.watch#62]
Hi there!

Thanks for this!

Updating the `fs` version this depends on and doing a new release would be greatly appreciated, as the [new `phoenix_live_reload` depends on some 2.12 version of it](https://github.com/phoenixframework/phoenix_live_reload/blob/master/mix.exs#L36). So this holds the update of that crucial dev dependency back :)

Thanks + cheers

**Comment by lpil** [comment]
Cool, I'll get on this. Some work needs to be done before I can cut a new release.

For now use the `override` option for that dep :) https://hexdocs.pm/mix/Mix.Tasks.Deps.html#module-options

**Comment by PragTob** [comment]
Thanks! :)

I'd rather avoid `override` if I can, and the update doesn't have any burning fixes I need so I guess I'm fine for a bit. (`override` always feels a bit dirty to me just like `!important` :P)

**Comment by lpil** [comment]
I think it's fine to override lazy library maintainers like me ;)

**Comment by lpil** [comment]
Hey @PragTob , could you try using the master branch please? Let me know if you have any problems.

**Comment by PragTob** [comment]
@lpil didn't have the time for a long running test, but an initial test worked very well! :)

**Comment by lpil** [comment]
Thank you :)

**Comment by petejkim** [comment]
https://github.com/phoenixframework/phoenix_live_reload/commit/e54bf6fb301436797ff589e0b76a047bb79b6870

**Comment by petejkim** [comment]
https://github.com/phoenixframework/phoenix_live_reload/commit/e54bf6fb301436797ff589e0b76a047bb79b6870

`phoenix_live_reload` rolled back `fs` to 0.9.1.

**Comment by zeroasterisk** [comment]
I agree - this is causing me problems:

```
$ mix deps.get
Running dependency resolution...

Failed to use "fs" (version 0.9.2) because
  mix_test_watch (versions 0.3.0 to 0.4.0) requires ~> 2.12
  phoenix_live_reload (version 1.0.8) requires ~> 0.9.1
  mix.lock specifies 0.9.2
```

**Comment by lpil** [comment]
Pushed a new version :)
