### ISSUE TITLE
Problem auto running on file save with v0.3

### ISSUE THREAD

**Issue by chbonser** [lpil/mix-test.watch#65]
I tried installing v0.3 on a brand new Phoenix project (Elixir v1.3.2, Phoenix 1.2, macOS 10.12.1).  The test suite runs once but saving a file in `./web` or `./test` does not rerun the test suite.  Dropping mix-test.watch back to v0.2.6 fixes the issue.

**Comment by lpil** [comment]
Thanks for the report. Could you share an example project with this issue?

**Comment by chbonser** [comment]
Sure. I'll try to throw something together this evening or tomorrow.

**Comment by lpil** [comment]
I just happen to have access to a mac at the moment, and it does seem to only run sometimes... How strange. I'll have to investigate.

**Comment by chbonser** [comment]
Let me know if there is something I can do to help.

**Comment by lpil** [comment]
Seems I introduced a funny little race condition that only happens on OSX. It's fixed in the latest version, thank you for the help!

It's quite hard to verify this stuff works on other platforms as it's very IO-y and I typically only use Linux!

**Comment by chbonser** [comment]
Works like a charm.  Thank you!
