### ISSUE TITLE
Docker support?

### ISSUE THREAD

**Issue by robvolk** [lpil/mix-test.watch#68]
I'm running my Phoenix app inside Docker and wondering if there's any way to get `test.watch` to work inside Docker?

It runs fine once, but doesn't detect filesystem changes.  I have the host application folder shared with the Container, so it should pick up the changes (live reload works with the Phoenix web server).

Has anyone tried this?

**Comment by lpil** [comment]
Could you give more information about your setup? Host OS, docker version, mix test.watch version etc :)

Also have you seen this? https://github.com/lpil/mix-test.watch/issues/61

**Comment by robvolk** [comment]
Thanks for the reply.  I read through the #61 and I updated both test.watch and phoenix_livereload, so should be good there.

I'm running OSX, test.watch v0.3.3, Docker version 17.03.0-ce, build 60ccb22.  This is the newer version of Docker that doesn't use Virtualbox.

When I boot up test.watch, I get an error [error] backend port not found: :inotifywait, but that shouldn't have to do with test.watch because you use something else to watch the filesystem right?   Any thoughts?

**Comment by lpil** [comment]
Ah yes, we leverage inotifywait for the file system events. I don't know how phoenix is pushing the front end updates without it. Hmm.

**Comment by robvolk** [comment]
I'm running it all with Docker Compose too, so I'm running with `docker-compose run app test.watch`

**Comment by lpil** [comment]
Is that notifywait available on the app image?

**Comment by xjunior** [comment]
I have the same problem here, and yes, inotifywait is available in my app image. This is the `Dockerfile`:

```bash
FROM elixir:1.4.0
ENV DEBIAN_FRONTEND=noninteractive

# Install hex
RUN mix local.hex --force

# Install rebar
RUN mix local.rebar --force

# Install inotify-tools
RUN apt-get update && apt-get install -y -q inotify-tools

# Set /app as workdir
RUN mkdir /app
ADD . /app
WORKDIR /app
```

**Comment by lpil** [comment]
Could you give detail on your docker setup please?

**Comment by lpil** [comment]
What OS are you running on, how have you installed docker, what version of docker are you using, and does inotifywait work if you use it directly within the container? :)

**Comment by xjunior** [comment]
> What OS are you running on,

MacOS 10.12.4

> how have you installed docker,

docker-toolbox

> what version of docker are you using,

```bash
$ VBoxManage -v
5.1.18r114002
$ docker -v
Docker version 17.04.0-ce, build 4845c56
$ docker-compose -v
docker-compose version 1.12.0, build b31ff33
```

> and does inotifywait work if you use it directly within the container?

It apparently does:

```bash
➜  quincy git:(master) ✗ docker-compose run web inotifywait .
Setting up watches.
Watches established.
```

> :)

😄

**Comment by stephanos** [comment]
fwiw, I _just_ ran into the same issue. When I change files, nothing happens:

```
Running tests...
Watches established.
Compiling 6 files (.ex)
Generated web app

.

Finished in 0.1 seconds
1 test, 0 failures

Randomized with seed 258017
```

I'm using

```
docker-compose run app /bin/bash -c "mix deps.get && mix test.watch"
```

with the image `shufo/phoenix:1.5.1-development` on latest OSX (10.12.6), Docker (17.06.02) and Docker Compose (1.14.0).

**Comment by stephanos** [comment]
How would I test that?

@xjunior did this, which also 'works' for me:

```
docker-compose run app inotifywait .
Setting up watches.
Watches established.
```

Well, nothing is triggered by file changes from the host. Didn't try to trigger it from inside the container.

**Comment by lpil** [comment]
If inotifywait cannot detect any file system events in your particular
docker setup we won't be able to determine when to run your tests. There's
no way for me to explore this I'm afraid as my setup is different to yours,
I cannot reproduce the problem.

If you're able to determine either what the issue is with your setup or
work out an inotifywait configuration that works we may be able to proceed.

**Comment by xjunior** [comment]
This issue was fixed to me by using dinghy instead of docket-machine directly. Dinghy has " volume sharing using NFS rather than built-in virtualbox/vmware file shares", which is not just fast, but also avoids a limitation with inodes. I found it was the issue in my dev machine while working with JavaScript and the files wouldn't get updated correctly on the container while if I open it on my machine they would be fine.

**Comment by stephanos** [comment]
@lpil fair enough. just wanted to give another data point. for the time being I'm using a watch process _outside_ of Docker to run my Docker test command. Adds a bit of overhead but works.

@xjunior interesting, thanks for sharing. will try that out.

**Comment by stephanos** [comment]
FYI this explains why it's not working: https://forums.docker.com/t/docker-for-mac-inotify-events-only-working-from-vim/18772/9

> It looks like mix test.watch uses the Erlang fs package which uses inotifywait here8. In this invocation, it is watching for the CLOSE_WRITE event which is not a file mutation event and which has no analog in OS X's FSEvents. We have a task to emulate CLOSE_WRITE on our roadmap but it is not currently supported as documented7. I recommend following Github issue https://github.com/docker/for-mac/issues/896 for updates. This feature is queued behind performance improvements so it has been slightly delayed.

**Comment by stephanos** [comment]
I also found this comment on https://github.com/synrc/fs very interesting:

> it appears that fs ~> 2.12 does correctly enable live reload on Docker for Mac containers (via listening to ATTRIB) without the need to add MODIFY.
...
> Since fs 2.12.x fixes the live reload issue with Docker containers on Docker for Mac that is present in 0.9.2, I think the best course of action is to close this issue and wait for upstream phoenix_livereload to move back to 2.12.x.

source: https://github.com/synrc/fs/issues/43#issuecomment-280863857

**Comment by spieker** [comment]
Related issue in Docker https://github.com/docker/for-mac/issues/896

**Comment by phyllisstein** [comment]
@stephanos That turns out to be 100% correct! I forked `mix-test.watch` and bumped `fs` to `2.12`---didn't break anything, and a Docker for Mac container with `inotify-tools` installed can see changes now. Thanks so much for the pointer.

**Comment by robvolk** [comment]
Thanks @phyllisstein your fork works!!  My feedback loop just got so much faster thanks to `test.watch`.   Can you open a PR?

**Comment by phyllisstein** [comment]
Ack, of course! Slipped my mind 😬. Done in #85.
