### ISSUE TITLE
Exclude tmp file created by Emacs

### ISSUE THREAD

**Issue by kisp** [lpil/mix-test.watch#72]
Hi,

I'm having trouble excluding a tmp file created by Emacs.

The file is actually a symbolic link that looks similiar to

```
.#post_test.exs -> user@machine.local.762
```

I have in my `config/config.exs`

``` elixir
if Mix.env == :dev do
  config :mix_test_watch, clear: true
  config :mix_test_watch, exclude: [~r/\.#/, ~r/~/]
end
```

Could you help me debug this?

It's really annoying, because this tmp file gets created very often (after saving and then changing a buffer), so I accidentally trigger more test runs than needed.

**Comment by lpil** [comment]
I'd recommend going inside your deps folder, putting in some logging, and then recompiling the deps. See what's happening in there :)

**Comment by cdegroot** [comment]
I have `exclude: [~r/\.#/]` and it works. However, it's mildly annoying to have to specify it in every project. With Git, I have global exclusions in my home directory - might it be an idea to have something similar for this?

**Comment by lpil** [comment]
I'm happy for this to be added to the default ignored patterns. Would you like to make a PR?

**Comment by cdegroot** [comment]
I'd be happy to, but do know that you'll end up with an ever-expanding list of editor/IDE specific patterns that way ;)

**Comment by lpil** [comment]
I'm happy to add patterns that cover the most common editors to provide a good out the box experience for most people. I don't think many editors create files that end with `.ex` anyway.

**Comment by cdegroot** [comment]
Like that?
