### ISSUE TITLE
Support @external_resource

### ISSUE THREAD

**Issue by adkron** [lpil/mix-test.watch#74]
Elixir provides a way to notify the compiler of an external file that is required for compilation. This file might be a resource that is used to generate code. `mix compile` knows it needs to recompile  a module if the external resource changes.

`mix test.watch` does not kick off test runs when an external resource changes. It would be externally helpful if it did run when an external resource changes.

**Comment by lpil** [comment]
This would require some very sophisticated integration, and I'm largely in the process of removing direct compiler integration. Could you instead add the file extension of the file in question to the `extra_extensions` configuration option?

```elixir
config :mix_test_watch,
  extra_extentions: [".foo"]
```

**Comment by adkron** [comment]
That would work. I didn't see that in the docs. I still think it could be a nice feature, but that one helps.

**Comment by adkron** [comment]
Oh, wait, that is the new feature you are proposing. I think that is okay. I don't like having to configure it twice, but I think it would work if you don't want compiler integration.

**Comment by lpil** [comment]
It should work today, could you try it out? Thanks :)

**Comment by adkron** [comment]
I tried again and it worked. I must have had a typo or something. I did find that it works by reading code the other day. Sorry I didn't get back to you. I do think that tying into external resource somehow could be nice to reduce "duplicate" configuration.

Excuse any typos. I'm on a phone. 

Amos King
Binary Noggin
