### ISSUE TITLE
Watch any kind of task

### ISSUE THREAD

**Issue by dylan-chong** [lpil/mix-test.watch#84]
It would be useful to be able to automatically update docs and/or dialyzer in addition to tests.

A suitable api would be `mix watch <taskname>`. Then we would be able to run `mix watch docs` or `mix watch dialyzer`.

It would also be called to be able to run multiple tasks as the files change (e.g test, dialyzer). I have no idea what a suitable command line api  would be. Perhaps the alternative for this would be for the programmer to just define a new task that runs to other tasks.

**Comment by lpil** [comment]
I would suggest the use of an external general purpose tool such as [Guard](https://github.com/guard/guard). :)

**Comment by dylan-chong** [comment]
Interesting, what do ya know https://rubygems.org/gems/guard-elixir 😛
