### ISSUE TITLE
Watch Templates

### ISSUE THREAD

**Issue by evadne** [lpil/mix-test.watch#92]
AFAIK `MixTestWatch.Path` holds `@elixir_source_endings` so it works on the basis of exclusion and re-runs tests when Elixir files have changed.

We have tests that verify template content and ideally I would want to make the configuration more flexible and allow us to include additional extensions.

Thoughts?

**Comment by lpil** [comment]
What would this allow that `extra_extensions` does not?

https://github.com/lpil/mix-test.watch/blob/master/lib/mix_test_watch/config.ex#L65

Thanks :)

**Comment by steakknife** [comment]
This works great:

```elixir
# end of config/dev.exs
config :mix_test_watch,
  # ...
  extra_extensions: [
    "slim",
    "slime"
  ]
```

**Comment by lpil** [comment]
Fab :)
