### ISSUE TITLE
ArgumentError when running `mix test.watch`

### ISSUE THREAD

**Issue by tmattio** [lpil/mix-test.watch#93]
Trying to run `mix test.watch` gives me the following output:

```
** (ArgumentError) argument error
    (stdlib) :ets.lookup_element(Ecto.Registry, nil, 3)
    (ecto) lib/ecto/registry.ex:18: Ecto.Registry.lookup/1
    (ecto) lib/ecto/adapters/sql/sandbox.ex:426: Ecto.Adapters.SQL.Sandbox.mode/2
    (elixir) lib/code.ex:677: Code.require_file/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
```

I am able to run the unit test with `mix test` though.

**Comment by lpil** [comment]
Can you supply an example project with the problem please? :)

**Comment by bijanbwb** [comment]
I'm not certain, but I think this happens if you try to add `mix-test.watch` to a Phoenix 1.4 application.

I was messing with the latest Elixir (1.7.1) and Phoenix (1.4) and ran into the same error.

You can try out the new dev version of Phoenix with the following:

```
mix archive.uninstall phx_new
mix archive.install https://github.com/phoenixframework/archives/raw/master/1.4-dev/phx_new.ez
```

Based on the errors mentioned above I wonder if it means the new version of Ecto is triggering the error.

As a side note, I'm using the `asdf` version manager so it's possible that could be an issue.

**Comment by ZombieHarvester** [comment]
Same problem

```
Running tests...
** (ArgumentError) argument error
    (stdlib) :ets.lookup_element(Ecto.Registry, nil, 3)
    lib/ecto/registry.ex:18: Ecto.Registry.lookup/1
    lib/ecto/adapters/sql/sandbox.ex:426: Ecto.Adapters.SQL.Sandbox.mode/2
    (elixir) lib/code.ex:767: Code.require_file/2
```

**Comment by lpil** [comment]
Could you provide a minimal example that reproduces the problem please?

**Comment by ZombieHarvester** [comment]
downgrading to 0.6.0 helped

**Comment by ZombieHarvester** [comment]
minimal example: https://github.com/ZombieHarvester/mix_test_issue_umbrella
```
mix deps.get
mix ecto.create
cd apps/mix_test_issue
mix test.watch
```

basically its an empty phoenix umbrella app with mix test watch package in core app

**Comment by lpil** [comment]
Thank you.

I take it by the fact this is an umbrella app that it works in a regular app? If that's not the case could you make a regular one please? :)

**Comment by ZombieHarvester** [comment]
Same problem in regular app
https://github.com/ZombieHarvester/mix_test_issue

**Comment by lpil** [comment]
Thank you!

**Comment by ZombieHarvester** [comment]
@lpil Thanks for the awesome tool
