### ISSUE TITLE
Could not run ExUnitProperties

### ISSUE THREAD

**Issue by iboss-ptk** [lpil/mix-test.watch#95]
While trying to run property-based testing with `mix test.watch`, it's giving me following error.

```
** (ArgumentError) could not fetch application environment :initial_size for application :stream_data because the application was not loaded/started. If your application depends on :stream_data at runtime, make sure to load/start it or list it under :extra_applications in your mix.exs file
```

So far, what I understand is the application environment initially specify in `stream_data`'s `mix.exs` is not be loaded properly.

Could anyone point me out where to start digging in. I'm happy to help :D

**Comment by lpil** [comment]
Which version are you using? Could you try with the latest version please? :)

**Comment by iboss-ptk** [comment]
Seems like upgrading to latest version solve the problem. Thank you :D

**Comment by lpil** [comment]
Thanks!
